spring:
  datasource:
    # Notice the ?sslmode=disable at the very end!
    url: jdbc:postgresql://notification_db:5432/notification_platform?sslmode=disable
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest